val:
  _target_: src.datasets.LibriSpeechDataset
  split: "test-clean"
  data_dir: ${hydra:runtime.cwd}/data/librispeech
  sample_rate: 16000
  segment_seconds: null
  random_crop: false
  instance_transforms: ${transforms.instance_transforms.inference}

test:
  _target_: src.datasets.LibriSpeechDataset
  split: "test-clean"
  data_dir: ${hydra:runtime.cwd}/data/librispeech
  sample_rate: 16000
  segment_seconds: null
  random_crop: false
  instance_transforms: ${transforms.instance_transforms.inference}
